# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-28 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180720_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
