# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-17 12:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=False, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions='mp3', message='Only mp3 files are allowed')]),
        ),
    ]
